/*
 * SOURCE: All 50 state legislatures — every upper (sldu) + lower (sldl) district.
 *
 * Districts come from the bundled OCD-id census_autogenerated CSVs
 * (data/us_sldu.csv, data/us_sldl.csv) — derived from official US Census TIGER,
 * so the ids match what geocodio returns at signup (the matching key). Bundled,
 * not fetched, so the seed is deterministic + auditable (you know exactly which
 * district set you seeded). Counts spot-checked: NY 63/150, CA 40/80, TX 31/150,
 * FL 40/120, NE 49/0 (unicameral). 2,019 upper + 5,053 lower = 7,072 districts.
 *
 * One office per district (resolution_method 'geocodio_district' — no GeoJSON
 * needed, geocodio resolves sldu/sldl). min_age is encoded from each state
 * constitution; the rest of eligibility stays display-only (eligibility_is_
 * encoded = false) since it's self-attested.
 */
const fs = require('fs');
const path = require('path');
const { STATE_FIPS } = require('../../ocd');
const U = require('../../upserts');

// Minimum age to SERVE, [upper, lower], per state constitution.
// Source: Wikipedia "Age of candidacy laws in the United States" (cross-checked
// vs the user's NY/CA/TX/FL). MT/VT = 18 (qualified-elector floor, no distinct
// statutory age). NE lower = null (unicameral — no lower house).
const AGE = {
    AL: [25, 21], AK: [25, 21], AZ: [25, 25], AR: [25, 21], CA: [18, 18], CO: [25, 25],
    CT: [18, 18], DE: [27, 24], FL: [21, 21], GA: [25, 21], HI: [25, 18], ID: [18, 18],
    IL: [21, 21], IN: [25, 21], IA: [25, 21], KS: [18, 18], KY: [30, 24], LA: [30, 18],
    ME: [25, 21], MD: [25, 21], MA: [25, 18], MI: [21, 21], MN: [21, 21], MS: [25, 21],
    MO: [30, 24], MT: [18, 18], NE: [21, null], NV: [21, 21], NH: [30, 18], NJ: [30, 21],
    NM: [25, 21], NY: [18, 18], NC: [25, 21], ND: [19, 18], OH: [18, 18], OK: [25, 21],
    OR: [21, 21], PA: [25, 21], RI: [18, 18], SC: [25, 21], SD: [21, 21], TN: [30, 21],
    TX: [26, 21], UT: [25, 25], VT: [18, 18], VA: [21, 21], WA: [18, 18], WV: [18, 18],
    WI: [18, 18], WY: [25, 21],
};
// term lengths (years): common defaults (most upper = 4yr, lower = 2yr). Refine per state later.
const TERM = { upper: 4, lower: 2 };
const SRC = 'https://github.com/opencivicdata/ocd-division-ids (census_autogenerated) + en.wikipedia.org/wiki/Age_of_candidacy_laws_in_the_United_States';

// Parse a bundled CSV → [{ ocd_id, state, num }]. We only need column 1 (the id),
// from which state + district number are derived — avoids any comma-in-name issues.
function parseDistricts(file, chamberKey) {
    const txt = fs.readFileSync(path.join(__dirname, 'data', file), 'utf8');
    const re = new RegExp(`state:([a-z]{2})/${chamberKey}:(.+)$`);
    const out = [];
    for (const line of txt.split('\n')) {
        const id = line.split(',')[0].trim();
        const m = id.match(re);
        if (m) out.push({ ocd_id: id, state: m[1].toUpperCase(), num: m[2] });
    }
    return out;
}

async function seed(client, { log }) {
    // parent lookup: state postal code → the existing type='state' jurisdiction id
    const sj = await client.query(`SELECT id, state_code FROM jurisdiction WHERE type = 'state'`);
    const parentByState = {};
    for (const r of sj.rows) parentByState[r.state_code] = r.id;

    const CHAMBERS = [
        { file: 'us_sldu.csv', key: 'sldu', chamber: 'upper', type: 'state_leg_upper', title: 'State Senate', office: 'State Senator', tag: 'SD' },
        { file: 'us_sldl.csv', key: 'sldl', chamber: 'lower', type: 'state_leg_lower', title: 'State House', office: 'State Representative', tag: 'HD' },
    ];

    let nUpper = 0, nLower = 0, skipped = 0;
    for (const c of CHAMBERS) {
        for (const d of parseDistricts(c.file, c.key)) {
            const parent = parentByState[d.state];
            const age = AGE[d.state];
            const minAge = age && (c.chamber === 'upper' ? age[0] : age[1]);
            // skip territories / DC / unicameral-lower / unknown
            if (!parent || minAge == null) { skipped += 1; continue; }

            const j = await U.upsertJurisdiction(client, {
                name: `${d.state} ${c.title} District ${d.num}`,
                type: c.type, parent_jurisdiction_id: parent, state_code: d.state,
                ocd_division_id: d.ocd_id, fips_code: STATE_FIPS[d.state],
            });
            await U.upsertOffice(client, {
                jurisdiction_id: j.id,
                office_name: `${d.state} ${c.office} District ${d.num}`,
                office_type: 'legislative', chamber: c.chamber,
                district_identifier: `${d.state}-${c.tag}-${d.num}`,
                district_name: `${d.state} ${c.title} District ${d.num}`,
                term_length: TERM[c.chamber], is_partisan: d.state !== 'NE', // NE is nonpartisan
                min_age: minAge, resolution_method: 'geocodio_district',
                citizenship_requirement: 'us_citizen',
                residency_requirement: 'inhabitant_of_district',
                eligibility_is_encoded: false,
                eligibility_notes: `Minimum age ${minAge} (state constitution). Confirm citizenship/residency with the state authority.`,
                eligibility_source_url: SRC,
            });
            if (c.chamber === 'upper') nUpper += 1; else nLower += 1;
        }
    }
    log?.(`  state legislatures: ${nUpper} upper + ${nLower} lower offices (${nUpper + nLower} total; skipped ${skipped})`);
}

module.exports = { seed, AGE };
